/**
 * PART B — Stage 9: THE COMPLETE VERB SYSTEM (ṣarf I) — Units 29–32.
 *   29 The Ten Forms (al-abwāb / al-awzān)
 *   30 The Muḍāri' Moods (marfū‘ / manṣūb / majzūm)
 *   31 Weak & Irregular Verbs (mithāl, ajwaf, nāqiṣ, muḍā‘af, mahmūz)
 *   32 Passive Voice (al-majhūl) & nā'ib al-fā‘il — checkpoint_after
 * Leans on the /roots engine. Run: DATABASE_URL=... node scripts/seed-stage-9.mjs
 */
import postgres from 'postgres';
const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) { console.error('ERROR: DATABASE_URL required'); process.exit(1); }
const sql = postgres(DATABASE_URL, { max: 1, connect_timeout: 30 });

const U29_L1 = { steps: [
  { type: 'teach', content: { title: 'The measuring stick: فَعَلَ', explanation: 'Every Arabic verb is measured against the pattern **فَعَلَ** using the letters ف-ع-ل (the *mīzān*, "the scale"). The three root letters slot into ف، ع، ل:\n\nك-ت-ب on فَعَلَ → كَتَبَ · ن-ص-ر → نَصَرَ', arabic: 'فَعَلَ = the scale', transliteration: 'fa‘ala', examples: [ { ar: 'كَتَبَ', tr: 'kataba', en: 'wrote (Form I)' }, { ar: 'خَلَقَ', tr: 'khalaqa', en: 'created (Form I)' } ], fun_fact: 'This is the science of ṣarf (morphology) — and the roots explorer at /roots is built entirely on it.' } },
  { type: 'teach', content: { title: 'One root, ten shapes', explanation: 'By adding letters and doubling, one root grows into as many as **ten "forms" (abwāb)** — each with a shade of meaning:\n\nForm I فَعَلَ (basic) → Form II فَعَّلَ (intensive/causative) → Form III فَاعَلَ (mutual)…', arabic: 'فَعَلَ · فَعَّلَ · فَاعَلَ', transliteration: 'fa‘ala · fa‘‘ala · faa‘ala', examples: [ { ar: 'عَلِمَ', tr: '‘alima', en: 'he knew (I)' }, { ar: 'عَلَّمَ', tr: '‘allama', en: 'he taught (II — caused to know)' } ], fun_fact: 'عَلِمَ "knew" → عَلَّمَ "taught" (made someone know). The doubled ع carries the causative punch.' } },
  { type: 'mcq', content: { question: 'Form II (فَعَّلَ, with a doubled middle letter) often means...', options: [ { text: 'intensive or causative ("make someone do")', correct: true }, { text: 'the passive', correct: false }, { text: 'a question', correct: false } ], explanation: 'عَلَّمَ (taught = made know), نَزَّلَ (sent down repeatedly). The shadda intensifies.' } },
  { type: 'match', content: { instruction: 'Match Form I → Form II (basic → intensive/causative)', pairs: [ { left: 'عَلِمَ (knew)', right: 'عَلَّمَ (taught)' }, { left: 'نَزَلَ (came down)', right: 'نَزَّلَ (sent down)' }, { left: 'كَبُرَ (was big)', right: 'كَبَّرَ (magnified)' } ] } },
  { type: 'teach', content: { title: 'The form idea', explanation: 'A root + a form pattern = a precise meaning. Next: Forms III–IV.', arabic: null, transliteration: null } },
]};
const U29_L2 = { steps: [
  { type: 'teach', content: { title: 'Forms III & IV', explanation: '**Form III — فَاعَلَ** (an alif after the first letter): mutual / directed-at action.\nقَاتَلَ (fought someone) · جَاهَدَ (strove).\n\n**Form IV — أَفْعَلَ** (a hamza-alif prefix): causative.\nأَنْزَلَ (sent down) · أَسْلَمَ (submitted) · أَخْرَجَ (brought out).', arabic: 'فَاعَلَ · أَفْعَلَ', transliteration: 'faa‘ala · af‘ala', examples: [ { ar: 'قَاتَلَ', tr: 'qaatala', en: 'fought (III)' }, { ar: 'أَنْزَلَ', tr: 'anzala', en: 'sent down (IV)' } ], fun_fact: 'أَسْلَمَ (Form IV, "submitted") is the root of "Islam" and "Muslim".' } },
  { type: 'mcq', content: { question: 'أَنْزَلَ ("he sent down") is which form?', options: [ { text: 'Form IV — أَفْعَلَ (causative, hamza prefix)', correct: true }, { text: 'Form II — فَعَّلَ', correct: false } ], explanation: 'The أ prefix on a 3-letter root marks Form IV (أَفْعَلَ).' } },
  { type: 'classify', content: { instruction: 'Which form?', categories: ['Form III (فَاعَلَ)', 'Form IV (أَفْعَلَ)'], items: [ { text: 'قَاتَلَ', category: 'Form III (فَاعَلَ)' }, { text: 'أَنْزَلَ', category: 'Form IV (أَفْعَلَ)' }, { text: 'جَاهَدَ', category: 'Form III (فَاعَلَ)' }, { text: 'أَخْرَجَ', category: 'Form IV (أَفْعَلَ)' } ], explanation: 'Alif after letter 1 = III; hamza prefix = IV.' } },
  { type: 'fill_blank', content: { sentence: 'أَسْلَمَ ("submitted") is Form ___, the causative pattern أَفْعَلَ.', correct_answer: 'IV', options: ['IV', 'II', 'X'], explanation: 'Form IV أَفْعَلَ — the source of "Islam".' } },
  { type: 'teach', content: { title: 'III & IV, learned', explanation: 'Mutual (فاعل) and causative (أفعل). Next: the reflexive forms V–VII.', arabic: null, transliteration: null } },
]};
const U29_L3 = { steps: [
  { type: 'teach', content: { title: 'Forms V, VI & VII', explanation: '**V — تَفَعَّلَ** (تَ + doubled): reflexive of II. تَذَكَّرَ (reminded himself), تَكَبَّرَ (was arrogant).\n**VI — تَفَاعَلَ** (تَ + alif): mutual over time. تَسَاءَلَ (asked one another).\n**VII — اِنْفَعَلَ** (اِنْ prefix): passive/result. اِنْقَلَبَ (turned over), اِنْشَقَّ (split).', arabic: 'تَفَعَّلَ · تَفَاعَلَ · اِنْفَعَلَ', transliteration: 'tafa‘‘ala · tafaa‘ala · infa‘ala', examples: [ { ar: 'تَذَكَّرَ', tr: 'tadhakkara', en: 'took heed (V)' }, { ar: 'اِنْشَقَّ', tr: 'inshaqqa', en: 'split apart (VII)' } ], fun_fact: 'اِذَّكَّرَ / تَذَكَّرَ — "will they not take heed?" (أَفَلَا تَذَكَّرُونَ) closes many ayat.' } },
  { type: 'mcq', content: { question: 'A verb starting with اِنْـ (like اِنْقَلَبَ) is which form?', options: [ { text: 'Form VII — اِنْفَعَلَ (result/passive)', correct: true }, { text: 'Form V — تَفَعَّلَ', correct: false } ], explanation: 'The اِنْـ prefix marks Form VII: "got turned over / split".' } },
  { type: 'match', content: { instruction: 'Match form to pattern', pairs: [ { left: 'Form V', right: 'تَفَعَّلَ' }, { left: 'Form VI', right: 'تَفَاعَلَ' }, { left: 'Form VII', right: 'اِنْفَعَلَ' } ] } },
  { type: 'classify', content: { instruction: 'Sort by form', categories: ['V (تَفَعَّلَ)', 'VI (تَفَاعَلَ)', 'VII (اِنْفَعَلَ)'], items: [ { text: 'تَكَبَّرَ', category: 'V (تَفَعَّلَ)' }, { text: 'تَسَاءَلَ', category: 'VI (تَفَاعَلَ)' }, { text: 'اِنْقَلَبَ', category: 'VII (اِنْفَعَلَ)' } ], explanation: 'تَ+shadda = V; تَ+alif = VI; اِنْ = VII.' } },
  { type: 'teach', content: { title: 'The تَ and اِنْ families', explanation: 'Reflexive, mutual, and result forms. Next: the powerhouse forms VIII & X.', arabic: null, transliteration: null } },
]};
const U29_L4 = { steps: [
  { type: 'teach', content: { title: 'Forms VIII & X', explanation: '**VIII — اِفْتَعَلَ** (اِ + ت infix): reflexive/effort. اِسْتَمَعَ (listened), اِتَّقَىٰ (guarded himself).\n**X — اِسْتَفْعَلَ** (اِسْتَ prefix): seeking/asking. اِسْتَغْفَرَ (sought forgiveness), اِسْتَكْبَرَ (deemed himself great).', arabic: 'اِفْتَعَلَ · اِسْتَفْعَلَ', transliteration: 'ifta‘ala · istaf‘ala', examples: [ { ar: 'اِسْتَغْفَرَ', tr: 'istaghfara', en: 'sought forgiveness (X)' }, { ar: 'اِسْتَمَعَ', tr: 'istama‘a', en: 'listened (VIII)' } ], fun_fact: 'X’s اِسْتَ prefix = "seek/ask for": اِسْتَغْفَرَ = ask for forgiveness, اِسْتَعَانَ = ask for help (إِيَّاكَ نَسْتَعِينُ!).' } },
  { type: 'mcq', content: { question: 'A verb starting with اِسْتَـ (like اِسْتَغْفَرَ) is which form?', options: [ { text: 'Form X — اِسْتَفْعَلَ (seeking/asking)', correct: true }, { text: 'Form VIII — اِفْتَعَلَ', correct: false } ], explanation: 'اِسْتَـ = "seek/ask for" → Form X.' } },
  { type: 'classify', content: { instruction: 'Identify the form (from real Quranic verbs)', categories: ['VIII (اِفْتَعَلَ)', 'X (اِسْتَفْعَلَ)'], items: [ { text: 'اِسْتَغْفَرَ', category: 'X (اِسْتَفْعَلَ)' }, { text: 'اِسْتَمَعَ', category: 'VIII (اِفْتَعَلَ)' }, { text: 'اِسْتَكْبَرَ', category: 'X (اِسْتَفْعَلَ)' }, { text: 'اِتَّقَىٰ', category: 'VIII (اِفْتَعَلَ)' } ], explanation: 'اِسْتَـ = X; the ت infix (اِفْتَعَلَ) = VIII.' } },
  { type: 'mcq', content: { question: 'يَسْتَغْفِرُونَ (present of اِسْتَغْفَرَ) means...', options: [ { text: 'they seek forgiveness', correct: true }, { text: 'they forgive', correct: false } ], explanation: 'Form X in the present: "they ASK for forgiveness".' } },
  { type: 'teach', content: { title: 'The 10 forms — surveyed', explanation: 'You can now name a verb’s form from its shape. Explore any root’s forms in /roots. Next: read forms live in the Quran.', arabic: null, transliteration: null } },
]};
const U29_L5 = { steps: [
  { type: 'teach', content: { title: 'Read the Quran 📖 — spot the form', explanation: '**تَنَزَّلُ الْمَلَائِكَةُ وَالرُّوحُ فِيهَا بِإِذْنِ رَبِّهِم** — "The angels and the Spirit descend therein by the permission of their Lord." (Al-Qadr 97:4)', arabic: 'تَنَزَّلُ الْمَلَائِكَةُ وَالرُّوحُ', transliteration: 'tanazzalul-malaa’ikatu war-rooḥ', quran_ref: 'Al-Qadr 97:4' } },
  { type: 'classify', content: { instruction: 'Identify the form of each Quranic verb', categories: ['Form IV (أَفْعَلَ)', 'Form X (اِسْتَفْعَلَ)', 'Form V/VI (تَـ)'], items: [ { text: 'أَنْزَلْنَا (We sent down)', category: 'Form IV (أَفْعَلَ)' }, { text: 'يَسْتَغْفِرُونَ (they seek forgiveness)', category: 'Form X (اِسْتَفْعَلَ)' }, { text: 'تَنَزَّلُ (descend)', category: 'Form V/VI (تَـ)' } ], explanation: 'أَنْزَلَ = IV; اِسْتَغْفَرَ = X; تَنَزَّلَ = a تَـ form (V).' } },
  { type: 'mcq', content: { question: 'أَنْزَلَ (IV, "sent down") and نَزَّلَ (II, "sent down gradually") share the root ن-ز-ل. What differs?', options: [ { text: 'The FORM — which shades the meaning', correct: true }, { text: 'The root', correct: false } ], explanation: 'Same root, different form = different nuance. That is the power of ṣarf.' } },
  { type: 'fill_blank', content: { sentence: 'يَسْتَغْفِرُونَ is Form ___ — "they seek forgiveness".', correct_answer: 'X', options: ['X', 'II', 'VII'], explanation: 'اِسْتَـ prefix → Form X (seeking).' } },
  { type: 'teach', content: { title: '🎉 Unit 29 complete!', explanation: 'The ten forms are yours — and they connect straight to the /roots engine. Next: the moods of the present verb.', arabic: null, transliteration: null } },
]};

const U30_L1 = { steps: [
  { type: 'teach', content: { title: 'The present verb has i‘rāb too', explanation: 'Unlike the past verb (which is fixed/mabnī), the **present verb (muḍāri‘) is flexible (mu‘rab)** — it has three states:\n\n**marfū‘** (default) → ḍamma: يَفْعَلُ\n**manṣūb** → fatḥa: يَفْعَلَ\n**majzūm** → sukūn: يَفْعَلْ', arabic: 'يَفْعَلُ · يَفْعَلَ · يَفْعَلْ', transliteration: 'yaf‘alu · yaf‘ala · yaf‘al', examples: [ { ar: 'يَعْلَمُ', tr: 'ya‘lamu', en: 'he knows (marfū‘, default)' } ], fun_fact: 'A plain present verb, with nothing in front, is marfū‘ (ḍamma). Certain particles pull it into naṣb or jazm.' } },
  { type: 'mcq', content: { question: 'The DEFAULT state of a present verb is...', options: [ { text: 'marfū‘ (ḍamma ending)', correct: true }, { text: 'majzūm (sukūn)', correct: false }, { text: 'jarr (kasra)', correct: false } ], explanation: 'يَفْعَلُ — ḍamma by default. Verbs never take jarr.' } },
  { type: 'classify', content: { instruction: 'What is the ending sign?', categories: ['marfū‘ (ḍamma)', 'manṣūb (fatḥa)', 'majzūm (sukūn)'], items: [ { text: 'يَعْلَمُ', category: 'marfū‘ (ḍamma)' }, { text: 'يَعْلَمَ', category: 'manṣūb (fatḥa)' }, { text: 'يَعْلَمْ', category: 'majzūm (sukūn)' } ], explanation: 'ـُ raf‘ · ـَ naṣb · ـْ jazm — for the present verb.' } },
  { type: 'teach', content: { title: 'Three moods', explanation: 'Default raf‘, then naṣb and jazm triggered by particles. Next: what causes naṣb.', arabic: null, transliteration: null } },
]};
const U30_L2 = { steps: [
  { type: 'teach', content: { title: 'What causes naṣb', explanation: 'Certain particles put the present verb into **naṣb** (fatḥa):\n\n**أَنْ** (to) · **لَنْ** (will never) · **كَيْ / لِـ** (in order to) · **حَتَّىٰ** (until/so that)\n\nلَنْ نُؤْمِنَ — "we will never believe" (نُؤْمِنَ = fatḥa).', arabic: 'أَنْ · لَنْ · كَيْ · لِـ · حَتَّىٰ', transliteration: 'an · lan · kay · li · ḥattaa', examples: [ { ar: 'لِيَعْبُدُونِ', tr: 'liya‘budoon', en: 'so that they worship Me' }, { ar: 'أَنْ تَصُومُوا', tr: 'an taṣoomoo', en: 'that you fast' } ], fun_fact: 'وَمَا خَلَقْتُ الْجِنَّ وَالْإِنْسَ إِلَّا لِيَعْبُدُونِ — "…except to worship Me". The لِـ puts يَعْبُدُ into naṣb.' } },
  { type: 'mcq', content: { question: 'After لَنْ, the present verb is in...', options: [ { text: 'naṣb (fatḥa) — "will never do"', correct: true }, { text: 'jazm', correct: false } ], explanation: 'لَنْ نُؤْمِنَ — لَنْ forces naṣb (fatḥa).' } },
  { type: 'classify', content: { instruction: 'Does the particle cause naṣb?', categories: ['Causes naṣb', 'Does NOT'], items: [ { text: 'لَنْ', category: 'Causes naṣb' }, { text: 'أَنْ', category: 'Causes naṣb' }, { text: 'لَمْ', category: 'Does NOT' }, { text: 'كَيْ', category: 'Causes naṣb' } ], explanation: 'أَنْ، لَنْ، كَيْ، لِـ، حَتَّىٰ → naṣb. (لَمْ causes jazm — next lesson.)' } },
  { type: 'fill_blank', content: { sentence: 'أُرِيدُ أَنْ أَعْبُدَ رَبِّي — أَعْبُدَ is in naṣb because of the particle ___.', correct_answer: 'أَنْ', options: ['أَنْ', 'لَمْ', 'قَدْ'], explanation: 'أَنْ ("to") pulls the verb into naṣb: "I want to worship…".' } },
  { type: 'teach', content: { title: 'Naṣb of the verb', explanation: 'أن، لن، كي، لـ، حتى → fatḥa. Next: what causes jazm.', arabic: null, transliteration: null } },
]};
const U30_L3 = { steps: [
  { type: 'teach', content: { title: 'What causes jazm', explanation: 'Other particles put the verb into **jazm** (sukūn — a "cut off" ending):\n\n**لَمْ** (did not) · **لَمَّا** (not yet) · **لَا** (do not! — prohibition) · **لِـ** (let… — command)\n\nلَمْ يَلِدْ — "He did not beget" (يَلِدْ = sukūn).', arabic: 'لَمْ · لَمَّا · لَا · لِـ', transliteration: 'lam · lammaa · laa · li', examples: [ { ar: 'لَمْ يَلِدْ', tr: 'lam yalid', en: 'He begets not' }, { ar: 'لِيُنفِقْ', tr: 'liyunfiq', en: 'let him spend' } ], fun_fact: 'لَمْ يَلِدْ وَلَمْ يُولَدْ (Al-Ikhlas) — لَمْ flips a present verb into a past denial AND jazms it to sukūn.' } },
  { type: 'mcq', content: { question: 'After لَمْ, the present verb is in...', options: [ { text: 'jazm (sukūn) — a past-meaning denial', correct: true }, { text: 'naṣb (fatḥa)', correct: false } ], explanation: 'لَمْ يَلِدْ — jazm (sukūn).' } },
  { type: 'classify', content: { instruction: 'naṣb or jazm particle?', categories: ['naṣb (fatḥa)', 'jazm (sukūn)'], items: [ { text: 'لَنْ', category: 'naṣb (fatḥa)' }, { text: 'لَمْ', category: 'jazm (sukūn)' }, { text: 'أَنْ', category: 'naṣb (fatḥa)' }, { text: 'لَا (prohibition)', category: 'jazm (sukūn)' } ], explanation: 'لن/أن → naṣb; لم/لا-nahiya/لـ-amr → jazm.' } },
  { type: 'fill_blank', content: { sentence: 'لَمْ يَكُنْ لَّهُ كُفُوًا أَحَدٌ — يَكُنْ is majzūm (sukūn) because of ___.', correct_answer: 'لَمْ', options: ['لَمْ', 'لَنْ', 'أَنْ'], explanation: 'لَمْ cuts the verb ending to sukūn (يَكُنْ).' } },
  { type: 'teach', content: { title: 'Jazm of the verb', explanation: 'لم، لمّا، لا-nahiya، لـ-amr → sukūn. Next: read all three moods in Al-Ikhlas.', arabic: null, transliteration: null } },
]};
const U30_L4 = { steps: [
  { type: 'teach', content: { title: 'Read the Quran 📖 — the moods in Al-Ikhlas', explanation: '**لَمْ يَلِدْ وَلَمْ يُولَدْ • وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ** — three present verbs, all cut to jazm by لَمْ.', arabic: 'لَمْ يَلِدْ وَلَمْ يُولَدْ', transliteration: 'lam yalid wa lam yoolad', quran_ref: 'Al-Ikhlas 112:3–4' } },
  { type: 'classify', content: { instruction: 'Tag the mood of each present verb', categories: ['majzūm (sukūn) — after لَمْ', 'marfū‘ (ḍamma) — default'], items: [ { text: 'يَلِدْ (لَمْ يَلِدْ)', category: 'majzūm (sukūn) — after لَمْ' }, { text: 'يُولَدْ (لَمْ يُولَدْ)', category: 'majzūm (sukūn) — after لَمْ' }, { text: 'يَعْلَمُ (وَاللّٰهُ يَعْلَمُ)', category: 'marfū‘ (ḍamma) — default' } ], explanation: 'لَمْ → jazm; nothing in front → the default raf‘.' } },
  { type: 'mcq', content: { question: 'لِيَعْبُدُوا رَبَّ هَٰذَا الْبَيْتِ — لِيَعْبُدُوا is...', options: [ { text: 'a command with لِـ ("let them worship")', correct: true }, { text: 'a past verb', correct: false } ], explanation: 'The لِـ of command (lām al-amr) jazms the verb: "let them worship".' } },
  { type: 'fill_blank', content: { sentence: 'A present verb with nothing pulling it is in ___ (its default state).', correct_answer: 'raf‘', options: ['raf‘', 'jazm', 'jarr'], explanation: 'Default = marfū‘ (ḍamma).' } },
  { type: 'teach', content: { title: '🎉 Unit 30 complete!', explanation: 'You parse the present verb’s three moods. Next: verbs whose weak letters shift and vanish.', arabic: null, transliteration: null } },
]};

const U31_L1 = { steps: [
  { type: 'teach', content: { title: 'Weak letters: و and ي', explanation: 'When a root contains **و** or **ي** (the "weak" letters), the verb bends. A root with a weak FIRST letter is called **mithāl** (like وَعَدَ, وَجَدَ). Its و often drops in the present:\n\nوَجَدَ → يَجِدُ (the و disappears!)', arabic: 'وَجَدَ → يَجِدُ', transliteration: 'wajada → yajidu', examples: [ { ar: 'وَعَدَ', tr: 'wa‘ada', en: 'promised → يَعِدُ' }, { ar: 'وَضَعَ', tr: 'waḍa‘a', en: 'placed → يَضَعُ' } ], fun_fact: 'Sound verbs (all strong letters, like كَتَبَ) never surprise you. Weak verbs are where the beauty — and the challenge — lives.' } },
  { type: 'mcq', content: { question: 'A verb whose FIRST root letter is و/ي (like وَجَدَ) is called...', options: [ { text: 'mithāl', correct: true }, { text: 'ajwaf (hollow)', correct: false }, { text: 'nāqiṣ', correct: false } ], explanation: 'Weak first letter = mithāl. Its weak letter often drops in the present (يَجِدُ).' } },
  { type: 'match', content: { instruction: 'Match past → present (watch the و vanish)', pairs: [ { left: 'وَجَدَ', right: 'يَجِدُ' }, { left: 'وَعَدَ', right: 'يَعِدُ' }, { left: 'وَضَعَ', right: 'يَضَعُ' } ] } },
  { type: 'fill_blank', content: { sentence: 'A root with a weak FIRST letter (و/ي) is a ___ verb.', correct_answer: 'mithāl', options: ['mithāl', 'ajwaf', 'mahmūz'], explanation: 'mithāl = "example" verb; its weak و tends to drop in the present.' } },
  { type: 'teach', content: { title: 'Weak-first verbs', explanation: 'mithāl — the و/ي at the start. Next: weak MIDDLE letter — the hollow verb.', arabic: null, transliteration: null } },
]};
const U31_L2 = { steps: [
  { type: 'teach', content: { title: 'Hollow verbs (ajwaf)', explanation: 'A weak MIDDLE letter makes an **ajwaf** ("hollow") verb — its middle turns into a long alif in the past:\n\nق-و-ل → **قَالَ** (said) · ك-و-ن → **كَانَ** (was) · خ-و-ف → **خَافَ** (feared)\n\nIn the present it shows again: يَقُولُ، يَكُونُ، يَخَافُ.', arabic: 'قَالَ (ق-و-ل)', transliteration: 'qaala', examples: [ { ar: 'قَالَ / يَقُولُ', tr: 'qaala / yaqoolu', en: 'said / says' }, { ar: 'كَانَ / يَكُونُ', tr: 'kaana / yakoonu', en: 'was / is' } ], fun_fact: 'قَالَ — the Quran’s most common verb — is hollow! Its root is ق-و-ل; the و hides as an alif in "qaala".' } },
  { type: 'mcq', content: { question: 'قَالَ comes from the root...', options: [ { text: 'ق-و-ل (a hollow verb — the و became alif)', correct: true }, { text: 'ق-ا-ل', correct: false } ], explanation: 'The alif in قَالَ is really a و. Hollow verbs hide their weak middle letter.' } },
  { type: 'classify', content: { instruction: 'Hollow (ajwaf) or sound (strong)?', categories: ['Hollow (weak middle)', 'Sound (all strong)'], items: [ { text: 'قَالَ (ق-و-ل)', category: 'Hollow (weak middle)' }, { text: 'كَتَبَ (ك-ت-ب)', category: 'Sound (all strong)' }, { text: 'خَافَ (خ-و-ف)', category: 'Hollow (weak middle)' }, { text: 'نَصَرَ (ن-ص-ر)', category: 'Sound (all strong)' } ], explanation: 'A long alif in the middle of a 3-letter past verb usually means a hidden و/ي.' } },
  { type: 'fill_blank', content: { sentence: 'كَانَ is hollow; its true root is ك-___-ن.', correct_answer: 'و', options: ['و', 'ا', 'ي'], explanation: 'ك-و-ن. The و surfaces in يَكُونُ.' } },
  { type: 'teach', content: { title: 'Hollow verbs', explanation: 'قال، كان، خاف — weak in the middle. Next: weak LAST letter — the defective verb.', arabic: null, transliteration: null } },
]};
const U31_L3 = { steps: [
  { type: 'teach', content: { title: 'Defective verbs (nāqiṣ) + doubled + hamzated', explanation: '**Nāqiṣ** — weak LAST letter, often ending in a soft alif/yā: دَعَا (called), هَدَىٰ (guided), تَلَا (recited).\n\nTwo more quick families:\n**Muḍā‘af** (doubled last two letters): رَدَّ (returned), مَدَّ (extended).\n**Mahmūz** (contains a hamza): سَأَلَ (asked), قَرَأَ (read).', arabic: 'هَدَىٰ · رَدَّ · قَرَأَ', transliteration: 'hadaa · radda · qara’a', examples: [ { ar: 'هَدَىٰ / يَهْدِي', tr: 'hadaa / yahdee', en: 'guided / guides (nāqiṣ)' }, { ar: 'قَرَأَ', tr: 'qara’a', en: 'read (mahmūz)' } ], fun_fact: 'اهْدِنَا (Guide us!) is from the nāqiṣ verb هَدَىٰ — its weak final letter drops in the command.' } },
  { type: 'mcq', content: { question: 'دَعَا, هَدَىٰ, تَلَا end in a weak final letter. They are called...', options: [ { text: 'nāqiṣ (defective)', correct: true }, { text: 'ajwaf (hollow)', correct: false } ], explanation: 'Weak LAST letter = nāqiṣ. Weak middle = ajwaf.' } },
  { type: 'classify', content: { instruction: 'Which weak family?', categories: ['nāqiṣ (weak last)', 'muḍā‘af (doubled)', 'mahmūz (hamza)'], items: [ { text: 'هَدَىٰ', category: 'nāqiṣ (weak last)' }, { text: 'رَدَّ', category: 'muḍā‘af (doubled)' }, { text: 'سَأَلَ', category: 'mahmūz (hamza)' }, { text: 'دَعَا', category: 'nāqiṣ (weak last)' } ], explanation: 'Weak-last = nāqiṣ; doubled = muḍā‘af; contains hamza = mahmūz.' } },
  { type: 'fill_blank', content: { sentence: 'قَرَأَ ("he read") contains a hamza, so it is a ___ verb.', correct_answer: 'mahmūz', options: ['mahmūz', 'ajwaf', 'nāqiṣ'], explanation: 'اقْرَأْ (Read!) is the command of this mahmūz verb.' } },
  { type: 'teach', content: { title: 'The weak families — surveyed', explanation: 'mithāl, ajwaf, nāqiṣ, muḍā‘af, mahmūz. Next: read weak verbs in the Quran.', arabic: null, transliteration: null } },
]};
const U31_L4 = { steps: [
  { type: 'teach', content: { title: 'Read the Quran 📖 — Surat ad-Duhā', explanation: '**مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ** — "Your Lord has not forsaken you, nor does He hate [you]." (Ad-Duha 93:3)', arabic: 'مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ', transliteration: 'maa wadda‘aka rabbuka wa maa qalaa', quran_ref: 'Ad-Duha 93:3' } },
  { type: 'classify', content: { instruction: 'Sort these Quranic verbs by weak type', categories: ['Hollow (ajwaf)', 'Defective (nāqiṣ)'], items: [ { text: 'قَالَ (said)', category: 'Hollow (ajwaf)' }, { text: 'قَلَىٰ (hated)', category: 'Defective (nāqiṣ)' }, { text: 'هَدَىٰ (guided)', category: 'Defective (nāqiṣ)' }, { text: 'كَانَ (was)', category: 'Hollow (ajwaf)' } ], explanation: 'قَلَىٰ / هَدَىٰ end weak (nāqiṣ); قَالَ / كَانَ are hollow.' } },
  { type: 'mcq', content: { question: 'قَلَىٰ ends in a soft alif. Its weak family is...', options: [ { text: 'nāqiṣ (defective — weak last letter)', correct: true }, { text: 'mithāl', correct: false } ], explanation: 'The final soft alif marks a nāqiṣ verb.' } },
  { type: 'fill_blank', content: { sentence: 'وَدَّعَكَ = وَدَّعَ + كَ. The كَ is the ___ ("you").', correct_answer: 'object', options: ['object', 'subject', 'preposition'], explanation: '"[He] forsook you" — كَ is the object of the Form-II verb وَدَّعَ.' } },
  { type: 'teach', content: { title: '🎉 Unit 31 complete!', explanation: 'Even the "irregular" verbs follow patterns now. Next: the passive — when the doer disappears.', arabic: null, transliteration: null } },
]};

const U32_L1 = { steps: [
  { type: 'teach', content: { title: 'When the doer disappears', explanation: 'The **passive** (al-majhūl, "the unknown") drops the doer and spotlights the receiver. In the past, the vowels change to **ḍamma-then-kasra**:\n\nكَتَبَ (wrote) → **كُتِبَ** (was written)\nخَلَقَ (created) → **خُلِقَ** (was created)\nقَالَ (said) → **قِيلَ** (it was said)', arabic: 'كُتِبَ · خُلِقَ · قِيلَ', transliteration: 'kutiba · khuliqa · qeela', examples: [ { ar: 'كُتِبَ عَلَيْكُمُ الصِّيَامُ', tr: 'kutiba ‘alaykumuṣ-ṣiyaam', en: 'fasting is prescribed for you' } ], fun_fact: 'كُتِبَ عَلَيْكُمُ الصِّيَامُ (Al-Baqarah 2:183) — "was prescribed": the doer (Allah) is understood, the focus is the command.' } },
  { type: 'mcq', content: { question: 'خُلِقَ (ḍamma-kasra) means...', options: [ { text: 'was created (passive)', correct: true }, { text: 'he created (active)', correct: false } ], explanation: 'The passive past pattern فُعِلَ: خُلِقَ = "was created".' } },
  { type: 'classify', content: { instruction: 'Active (he did) or passive (was done)?', categories: ['Active (فَعَلَ)', 'Passive (فُعِلَ)'], items: [ { text: 'خَلَقَ', category: 'Active (فَعَلَ)' }, { text: 'خُلِقَ', category: 'Passive (فُعِلَ)' }, { text: 'كُتِبَ', category: 'Passive (فُعِلَ)' }, { text: 'كَتَبَ', category: 'Active (فَعَلَ)' } ], explanation: 'ḍamma-then-kasra (فُعِلَ) = passive.' } },
  { type: 'fill_blank', content: { sentence: 'قَالَ (said) becomes the passive ___ ("it was said").', correct_answer: 'قِيلَ', options: ['قِيلَ', 'قَالُوا', 'قُلْ'], explanation: 'Hollow passive: قِيلَ = "it was said".' } },
  { type: 'teach', content: { title: 'The passive past', explanation: 'فُعِلَ = "was done". Next: who takes the subject’s place.', arabic: null, transliteration: null } },
]};
const U32_L2 = { steps: [
  { type: 'teach', content: { title: 'The stand-in subject', explanation: 'With no doer, the RECEIVER steps up to become the grammatical subject — the **nāʾib al-fāʿil** ("deputy of the doer"). It takes **raf‘** (like a fāʿil):\n\nكُتِبَ **الْكِتَابُ** — "the book was written" (الْكِتَابُ = raf‘).', arabic: 'نَائِب الفَاعِل', transliteration: 'naa’ib al-faa‘il', examples: [ { ar: 'كُتِبَ عَلَيْكُمُ الصِّيَامُ', tr: '…aṣ-ṣiyaamu', en: 'the fasting (raf‘) was prescribed' } ], fun_fact: 'The old object becomes the new subject — so it switches from naṣb to raf‘.' } },
  { type: 'mcq', content: { question: 'In كُتِبَ عَلَيْكُمُ الصِّيَامُ, why is الصِّيَامُ in raf‘ (ḍamma)?', options: [ { text: 'It is the nāʾib al-fāʿil (the stand-in subject)', correct: true }, { text: 'It is the object', correct: false } ], explanation: 'With the doer gone, "the fasting" becomes the subject → raf‘.' } },
  { type: 'classify', content: { instruction: 'Is the highlighted word a doer or a stand-in subject?', categories: ['fāʿil (active doer)', 'nāʾib al-fāʿil (passive subject)'], items: [ { text: 'اللّٰهُ in خَلَقَ اللّٰهُ', category: 'fāʿil (active doer)' }, { text: 'الصِّيَامُ in كُتِبَ … الصِّيَامُ', category: 'nāʾib al-fāʿil (passive subject)' }, { text: 'رَبُّكَ in قَالَ رَبُّكَ', category: 'fāʿil (active doer)' } ], explanation: 'Active verb → fāʿil; passive verb → nāʾib al-fāʿil. Both are raf‘.' } },
  { type: 'fill_blank', content: { sentence: 'The stand-in subject of a passive verb takes the ___ case.', correct_answer: 'raf‘', options: ['raf‘', 'naṣb', 'jarr'], explanation: 'nāʾib al-fāʿil = marfū‘ (like the doer it replaces).' } },
  { type: 'teach', content: { title: 'The deputy subject', explanation: 'No doer → the receiver is promoted to raf‘. Next: the passive in the present tense.', arabic: null, transliteration: null } },
]};
const U32_L3 = { steps: [
  { type: 'teach', content: { title: 'The present passive', explanation: 'In the present, the passive takes a **ḍamma prefix and a fatḥa before the last letter** (يُفْعَلُ):\n\nيَقُولُ (says) → **يُقَالُ** (is said)\nيَنْفُخُ (blows) → **يُنْفَخُ** (is blown)\nيَبْعَثُ (raises) → **يُبْعَثُونَ** (they are raised)', arabic: 'يُقَالُ · يُنْفَخُ', transliteration: 'yuqaalu · yunfakhu', examples: [ { ar: 'يُنفَخُ فِي الصُّورِ', tr: 'yunfakhu fiṣ-ṣoor', en: 'the Trumpet is blown' } ], fun_fact: 'وَنُفِخَ فِي الصُّورِ — "and the Trumpet is blown": a passive that hides the blower to magnify the event.' } },
  { type: 'mcq', content: { question: 'يُبْعَثُونَ means...', options: [ { text: 'they are raised (passive)', correct: true }, { text: 'they raise (active)', correct: false } ], explanation: 'The ḍamma prefix marks the present passive: "they are resurrected".' } },
  { type: 'classify', content: { instruction: 'Present active or present passive?', categories: ['Active (يَفْعَلُ)', 'Passive (يُفْعَلُ)'], items: [ { text: 'يَعْلَمُ (he knows)', category: 'Active (يَفْعَلُ)' }, { text: 'يُقَالُ (it is said)', category: 'Passive (يُفْعَلُ)' }, { text: 'يُبْعَثُونَ (are raised)', category: 'Passive (يُفْعَلُ)' }, { text: 'يَقُولُ (he says)', category: 'Active (يَفْعَلُ)' } ], explanation: 'A ḍamma on the prefix letter (يُـ) signals the present passive.' } },
  { type: 'fill_blank', content: { sentence: 'The present passive pattern is يُفْعَ___ (ḍamma prefix, fatḥa before the last letter).', correct_answer: 'لُ', options: ['لُ', 'لَ', 'لْ'], explanation: 'يُفْعَلُ — e.g. يُقَالُ, يُنْفَخُ.' } },
  { type: 'teach', content: { title: 'Present passive', explanation: 'يُفْعَلُ = "is done". Next: read the passive in the Quran.', arabic: null, transliteration: null } },
]};
const U32_L4 = { steps: [
  { type: 'teach', content: { title: 'Read the Quran 📖 — the passive of the Last Day', explanation: '**وَإِذَا الْمَوْءُودَةُ سُئِلَتْ • بِأَيِّ ذَنبٍ قُتِلَتْ** — "And when the buried-alive girl is asked, for what sin she was killed." (At-Takwir 81:8–9)', arabic: 'وَإِذَا الْمَوْءُودَةُ سُئِلَتْ', transliteration: 'wa idhal-maw’oodatu su’ilat', quran_ref: 'At-Takwir 81:8–9' } },
  { type: 'classify', content: { instruction: 'Tag the passive verbs', categories: ['Passive (was done)', 'Active (did)'], items: [ { text: 'سُئِلَتْ (was asked)', category: 'Passive (was done)' }, { text: 'قُتِلَتْ (was killed)', category: 'Passive (was done)' }, { text: 'خَلَقَ (created)', category: 'Active (did)' } ], explanation: 'سُئِلَتْ, قُتِلَتْ — ḍamma-kasra passives, with ـتْ for the feminine subject.' } },
  { type: 'mcq', content: { question: 'In الْمَوْءُودَةُ سُئِلَتْ, الْمَوْءُودَةُ (the buried girl) is the...', options: [ { text: 'nāʾib al-fāʿil — raf‘ (she is asked)', correct: true }, { text: 'doer of the asking', correct: false } ], explanation: 'She receives the action; with the passive she becomes the raf‘ subject.' } },
  { type: 'fill_blank', content: { sentence: 'قُتِلَتْ = passive "was killed" + ـتْ for a ___ subject.', correct_answer: 'feminine', options: ['feminine', 'plural', 'masculine'], explanation: 'The ـتْ agrees with the feminine الْمَوْءُودَة.' } },
  { type: 'teach', content: { title: '🏆 STAGE 9 COMPLETE — the verb system mastered!', explanation: 'You now read a verb’s **form** (I–X), **mood** (raf‘/naṣb/jazm), **weak family**, and **voice** (active/passive) — the full science of ṣarf that powers the /roots explorer.\n\nNext in the mastery track: **derived nouns** — how verbs blossom into maṣdar, ism fāʿil, ism tafḍīl, and more.', arabic: null, transliteration: null } },
]};

const U29_VOCAB = [ ['عَلَّمَ','‘allama','he taught (II)','feel',null,null,'Al-Baqarah 2:31',1], ['قَاتَلَ','qaatala','he fought (III)','feel',null,null,'Al-Baqarah 2:190',2], ['اِسْتَغْفَرَ','istaghfara','he sought forgiveness (X)','feel',null,null,'An-Nasr 110:3',1], ['تَنَزَّلَ','tanazzala','it descended (V)','feel',null,null,'Al-Qadr 97:4',2], ['أَسْلَمَ','aslama','he submitted (IV)','feel',null,null,'Al-Baqarah 2:112',1] ];
const U30_VOCAB = [ ['أَنْ','an','to (naṣbs the verb)','harf',null,null,'Al-Baqarah 2:184',1], ['لَنْ','lan','will never (naṣbs)','harf',null,null,'Al-Baqarah 2:80',1], ['لِـ','li','so that / let (naṣb or jazm)','harf',null,null,'Quraysh 106:3',1], ['حَتَّىٰ','ḥattaa','until / so that','harf',null,null,'Al-Baqarah 2:187',2] ];
const U31_VOCAB = [ ['وَجَدَ','wajada','he found (mithāl)','feel',null,null,'Ad-Duha 93:6',1], ['قَالَ','qaala','he said (ajwaf: ق-و-ل)','feel',null,null,'Al-Baqarah 2:30',1], ['هَدَىٰ','hadaa','he guided (nāqiṣ)','feel',null,null,'Al-A‘la 87:3',1], ['قَرَأَ','qara’a','he read (mahmūz)','feel',null,null,'Al-Alaq 96:1',1] ];
const U32_VOCAB = [ ['كُتِبَ','kutiba','it was prescribed (passive)','feel',null,null,'Al-Baqarah 2:183',1], ['خُلِقَ','khuliqa','it was created (passive)','feel',null,null,'Al-Anbiya 21:37',1], ['قِيلَ','qeela','it was said (passive)','feel',null,null,'Al-Baqarah 2:11',1], ['يُبْعَثُونَ','yub‘athoon','they are raised (passive)','feel',null,null,'Al-A‘raf 7:14',2] ];

const UNIT_DEFS = [
  [29,'ten-forms','The Ten Forms','الأَبْوَاب العَشَرَة','🔟','#8B7BD8',false,'How one root grows into ten verb forms (abwāb) — powered by /roots.'],
  [30,'mudari-moods','The Present-Verb Moods','أَحْوَال المُضَارِع','🎚️','#5FB57A',false,'The muḍāri‘ in raf‘, naṣb, and jazm — and what triggers each.'],
  [31,'weak-verbs','Weak & Irregular Verbs','الفِعْل المُعْتَلّ','🌀','#6BA8D4',false,'mithāl, ajwaf, nāqiṣ, muḍā‘af, mahmūz — the verbs that bend.'],
  [32,'passive','The Passive Voice','المَبْنِيّ لِلْمَجْهُول','🎭','#C77DBB',true,'al-majhūl and nāʾib al-fāʿil — when the doer disappears.'],
];
const LESSONS = [
  [29,'form-i-ii','The Scale & Form II',1,U29_L1,15],[29,'forms-iii-iv','Forms III & IV',2,U29_L2,15],[29,'forms-v-vii','Forms V–VII',3,U29_L3,15],[29,'forms-viii-x','Forms VIII & X',4,U29_L4,15],[29,'read-quran-forms','Read the Quran: Spot the Form',5,U29_L5,20],
  [30,'mudari-default','The Three Moods',1,U30_L1,15],[30,'mudari-nasb','What Causes Naṣb',2,U30_L2,15],[30,'mudari-jazm','What Causes Jazm',3,U30_L3,15],[30,'read-quran-moods','Read the Quran: The Moods',4,U30_L4,20],
  [31,'mithal','Weak-First Verbs',1,U31_L1,15],[31,'ajwaf','Hollow Verbs',2,U31_L2,15],[31,'naqis','Defective & More',3,U31_L3,15],[31,'read-quran-weak','Read the Quran: Ad-Duhā',4,U31_L4,20],
  [32,'passive-past','When the Doer Disappears',1,U32_L1,15],[32,'naib-fail','The Stand-In Subject',2,U32_L2,15],[32,'passive-present','The Present Passive',3,U32_L3,15],[32,'read-quran-passive','Read the Quran: The Passive',4,U32_L4,20],
];
const VOCAB = [[29,U29_VOCAB],[30,U30_VOCAB],[31,U31_VOCAB],[32,U32_VOCAB]];

async function main() {
  const id = {};
  for (const [so,slug,title,titleAr,emoji,color,cp,desc] of UNIT_DEFS) {
    const [r] = await sql`INSERT INTO learning_units (slug,title,title_ar,description,icon_emoji,color,sort_order,checkpoint_after)
      VALUES (${slug},${title},${titleAr},${desc},${emoji},${color},${so},${cp})
      ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title,title_ar=EXCLUDED.title_ar,description=EXCLUDED.description,icon_emoji=EXCLUDED.icon_emoji,color=EXCLUDED.color,sort_order=EXCLUDED.sort_order,checkpoint_after=EXCLUDED.checkpoint_after
      RETURNING id,sort_order`;
    id[so]=r.id; console.log(`Unit ${so} [${slug}] → ${r.id}`);
  }
  for (const [us,slug,title,so,content,xp] of LESSONS) {
    await sql`INSERT INTO learning_lessons (unit_id,slug,title,sort_order,lesson_type,content,xp_reward)
      VALUES (${id[us]},${slug},${title},${so},'standard',${sql.json(content)},${xp})
      ON CONFLICT (unit_id,slug) DO UPDATE SET title=EXCLUDED.title,sort_order=EXCLUDED.sort_order,content=EXCLUDED.content,xp_reward=EXCLUDED.xp_reward`;
    console.log(`  ✓ U${us} ${title} (${content.steps.length} steps)`);
  }
  for (const [us,vocab] of VOCAB) {
    await sql`DELETE FROM vocabulary_bank WHERE unit_id=${id[us]}`;
    for (const [ar,tr,en,type,g,n,ref,d] of vocab)
      await sql`INSERT INTO vocabulary_bank (word_ar,transliteration,english,word_type,gender,number,unit_id,quranic_ref,difficulty) VALUES (${ar},${tr},${en},${type},${g},${n},${id[us]},${ref},${d})`;
    console.log(`  ✓ ${vocab.length} vocab for U${us}`);
  }
  const [f] = await sql`SELECT id FROM learning_lessons WHERE unit_id=${id[29]} ORDER BY sort_order LIMIT 1`;
  const un = await sql`WITH prev AS (SELECT l.id FROM learning_lessons l JOIN learning_units u ON u.id=l.unit_id WHERE u.sort_order=28), fin AS (SELECT p.user_id FROM user_lesson_progress p JOIN prev ON prev.id=p.lesson_id WHERE p.status='completed' GROUP BY p.user_id HAVING count(*)=(SELECT count(*) FROM prev)) INSERT INTO user_lesson_progress (user_id,lesson_id,status) SELECT fin.user_id,${f.id},'available' FROM fin ON CONFLICT (user_id,lesson_id) DO NOTHING RETURNING user_id`;
  console.log(`  ✓ Unlocked U29 L1 for ${un.length} finishers of U28`);
  const [t]=await sql`SELECT count(*)::int u FROM learning_units`,[tl]=await sql`SELECT count(*)::int l FROM learning_lessons`;
  console.log(`TOTAL: ${t.u} units, ${tl.l} lessons.`);
}
main().then(()=>sql.end()).catch(async e=>{console.error('FAIL:',e.message);await sql.end();process.exit(1);});
